var testFla = {
  "type": "dom",
  "width": 1024,
  "height": 768,
  "x": 0,
  "y": 0,
  "layers": [{
    "type": "layer",
    "x": 0,
    "y": 0,
    "name": "图层 1",
    "frameLen": 1,
    "frames": [{
      "type": "frame",
      "x": 0,
      "y": 0,
      "startFrame": 0,
      "elements": [{
        "type": "movie clip",
        "blendMode": "normal",
        "x": 73.45,
        "y": 110.55,
        "reg": [0, 1],
        "width": 870,
        "height": 587,
        "transformX": 488.95,
        "transformY": 265,
        "scaleX": 1,
        "scaleY": 1,
        "rotation": 0,
        "dom": [{
          "type": "layer",
          "x": 0,
          "y": 0,
          "name": "背景图",
          "frameLen": 1,
          "frames": [{
            "type": "frame",
            "x": 0,
            "y": 0,
            "startFrame": 0,
            "elements": [{
              "type": "bitmap",
              "src": "testFla_家园牧场背景组.png.png",
              "x": 0,
              "y": 0,
              "reg": [0, 1],
              "width": 870,
              "height": 587,
              "transformX": 435,
              "transformY": 293.5,
              "scaleX": 1,
              "scaleY": 1,
              "rotation": 0
            },
            {
              "type": "bitmap",
              "src": "testFla_牧场.png.png",
              "x": 19.45,
              "y": 48.35,
              "reg": [0, 1],
              "width": 831,
              "height": 422,
              "transformX": 434.95,
              "transformY": 259.35,
              "scaleX": 1,
              "scaleY": 1,
              "rotation": 0
            }],
            "duration": 1
          }]
        },
        {
          "type": "layer",
          "x": 0,
          "y": 0,
          "name": "房子",
          "frameLen": 1,
          "frames": [{
            "type": "frame",
            "x": 0,
            "y": 0,
            "startFrame": 0,
            "elements": [{
              "type": "movie clip",
              "blendMode": "normal",
              "x": 578,
              "y": 213.35,
              "reg": [1, 0],
              "width": 432,
              "height": 174,
              "transformX": 668,
              "transformY": 303.35,
              "scaleX": 1,
              "scaleY": 1,
              "rotation": 0,
              "name": "_newHouse",
              "dom": [{
                "type": "layer",
                "x": 0,
                "y": 0,
                "name": "图层 2",
                "frameLen": 5,
                "frames": [{
                  "type": "frame",
                  "x": 0,
                  "y": 0,
                  "startFrame": 0,
                  "elements": [],
                  "duration": 1
                },
                {
                  "type": "frame",
                  "x": 0,
                  "y": 0,
                  "startFrame": 1,
                  "elements": [],
                  "duration": 1
                },
                {
                  "type": "frame",
                  "x": 0,
                  "y": 0,
                  "startFrame": 2,
                  "elements": [],
                  "duration": 1
                },
                {
                  "type": "frame",
                  "x": 0,
                  "y": 0,
                  "startFrame": 3,
                  "elements": [],
                  "duration": 1
                },
                {
                  "type": "frame",
                  "x": 0,
                  "y": 0,
                  "startFrame": 4,
                  "elements": [],
                  "duration": 1
                }]
              },
              {
                "type": "layer",
                "x": 0,
                "y": 0,
                "name": "图层 1",
                "frameLen": 5,
                "frames": [{
                  "type": "frame",
                  "x": 0,
                  "y": 0,
                  "startFrame": 0,
                  "elements": [{
                    "type": "movie clip",
                    "blendMode": "normal",
                    "x": 0,
                    "y": 0,
                    "reg": [1, 0],
                    "width": 432,
                    "height": 174,
                    "transformX": 1.35,
                    "transformY": 0.5,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_house",
                    "dom": [{
                      "type": "layer",
                      "x": 0,
                      "y": 0,
                      "name": "图层 2",
                      "frameLen": 5,
                      "frames": [{
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 0,
                        "elements": [],
                        "duration": 5
                      }]
                    },
                    {
                      "type": "layer",
                      "x": 0,
                      "y": 0,
                      "name": "图层 1",
                      "frameLen": 5,
                      "frames": [{
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 0,
                        "elements": [{
                          "type": "bitmap",
                          "src": "testFla_wopeng!!_wopeng5.png.png",
                          "x": -217,
                          "y": -87,
                          "reg": [0, 1],
                          "width": 432,
                          "height": 174,
                          "transformX": -1,
                          "transformY": 0,
                          "scaleX": 1,
                          "scaleY": 1,
                          "rotation": 0
                        }],
                        "duration": 1
                      },
                      {
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 1,
                        "elements": [{
                          "type": "bitmap",
                          "src": "testFla_wopeng!!_wopeng4.png.png",
                          "x": -230,
                          "y": -79,
                          "reg": [0, 1],
                          "width": 459,
                          "height": 167,
                          "transformX": -0.5,
                          "transformY": 4.5,
                          "scaleX": 1,
                          "scaleY": 1,
                          "rotation": 0
                        }],
                        "duration": 1
                      },
                      {
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 2,
                        "elements": [{
                          "type": "bitmap",
                          "src": "testFla_wopeng!!_wopeng3.png.png",
                          "x": -250,
                          "y": -97,
                          "reg": [0, 1],
                          "width": 501,
                          "height": 194,
                          "transformX": 0.5,
                          "transformY": 0,
                          "scaleX": 1,
                          "scaleY": 1,
                          "rotation": 0
                        }],
                        "duration": 1
                      },
                      {
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 3,
                        "elements": [{
                          "type": "bitmap",
                          "src": "testFla_wopeng!!_wopeng2.png.png",
                          "x": -276,
                          "y": -105,
                          "reg": [0, 1],
                          "width": 551,
                          "height": 210,
                          "transformX": -0.5,
                          "transformY": 0,
                          "scaleX": 1,
                          "scaleY": 1,
                          "rotation": 0
                        }],
                        "duration": 1
                      },
                      {
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 4,
                        "elements": [{
                          "type": "bitmap",
                          "src": "testFla_wopeng!!_wopeng1.png.png",
                          "x": -280,
                          "y": -105,
                          "reg": [0, 1],
                          "width": 559,
                          "height": 210,
                          "transformX": -0.5,
                          "transformY": 0,
                          "scaleX": 1,
                          "scaleY": 1,
                          "rotation": 0
                        }],
                        "duration": 1
                      }]
                    }],
                    "frameLen": 5
                  }],
                  "duration": 5
                }]
              }],
              "frameLen": 5
            },
            {
              "type": "movie clip",
              "blendMode": "normal",
              "x": 363.95,
              "y": 61.85,
              "reg": [0, 1],
              "width": 143,
              "height": 70,
              "transformX": 438.95,
              "transformY": 133.35,
              "scaleX": 1,
              "scaleY": 1,
              "rotation": 0,
              "name": "_houseTips",
              "dom": [{
                "type": "layer",
                "x": 0,
                "y": 0,
                "name": "图层 2",
                "frameLen": 40,
                "frames": [{
                  "type": "frame",
                  "x": 0,
                  "y": 0,
                  "startFrame": 0,
                  "elements": [{
                    "type": "bitmap",
                    "src": "testFla_开始界面(2).psd_资源_图层_1.png",
                    "x": 0,
                    "y": 0,
                    "reg": [0, 1],
                    "width": 143,
                    "height": 70,
                    "transformX": 71.5,
                    "transformY": 35,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0
                  },
                  {
                    "type": "text",
                    "x": 4,
                    "y": 14.7,
                    "reg": [0, 1],
                    "width": 136,
                    "height": 37.3,
                    "transformX": 72,
                    "transformY": 33.35,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_houseTipsText",
                    "textType": "dynamic",
                    "fontSize": 12,
                    "fillColor": "#ffffff",
                    "fontName": "宋体",
                    "alignment": "center",
                    "embedString": "点击窝棚饲养动物",
                    "lineType": "multiline"
                  }],
                  "duration": 40
                }]
              }],
              "frameLen": 40
            }],
            "duration": 1
          }]
        },
        {
          "type": "layer",
          "x": 0,
          "y": 0,
          "name": "冒泡",
          "frameLen": 1,
          "frames": [{
            "type": "frame",
            "x": 0,
            "y": 0,
            "startFrame": 0,
            "elements": [{
              "type": "movie clip",
              "blendMode": "normal",
              "x": 349.8,
              "y": 252.35,
              "reg": [1, 1],
              "width": 144,
              "height": 50,
              "transformX": 424.85,
              "transformY": 262.35,
              "scaleX": 1,
              "scaleY": 1,
              "rotation": 0,
              "name": "_countDown",
              "dom": [{
                "type": "layer",
                "x": 0,
                "y": 0,
                "name": "图层 1",
                "frameLen": 1,
                "frames": [{
                  "type": "frame",
                  "x": 0,
                  "y": 0,
                  "startFrame": 0,
                  "elements": [{
                    "type": "bitmap",
                    "src": "testFla_边框.png.png",
                    "x": 0,
                    "y": 0,
                    "reg": [0, 1],
                    "width": 96,
                    "height": 50,
                    "transformX": 48,
                    "transformY": 25,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0
                  },
                  {
                    "type": "button",
                    "x": 1,
                    "y": 2,
                    "reg": [0, 1],
                    "width": 94,
                    "height": 45,
                    "transformX": 120,
                    "transformY": 68,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "src": "testFla_冒泡底图元件.png"
                  }],
                  "duration": 1
                }]
              },
              {
                "type": "layer",
                "x": 0,
                "y": 0,
                "name": "图层 2",
                "frameLen": 1,
                "frames": [{
                  "type": "frame",
                  "x": 0,
                  "y": 0,
                  "startFrame": 0,
                  "elements": [{
                    "type": "text",
                    "x": -23,
                    "y": 10.2,
                    "reg": [0, 1],
                    "width": 144,
                    "height": 16,
                    "transformX": 49,
                    "transformY": 18.2,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_countDownText",
                    "textType": "dynamic",
                    "fontSize": 12,
                    "fillColor": "#ffffff",
                    "fontName": "宋体",
                    "alignment": "center",
                    "embedString": "",
                    "lineType": "multiline"
                  }],
                  "duration": 1
                }]
              }],
              "frameLen": 1
            }],
            "duration": 1
          }]
        },
        {
          "type": "layer",
          "x": 0,
          "y": 0,
          "name": "动物头像界面",
          "frameLen": 1,
          "frames": [{
            "type": "frame",
            "x": 0,
            "y": 0,
            "startFrame": 0,
            "elements": [{
              "type": "movie clip",
              "blendMode": "normal",
              "x": 166,
              "y": 397.95,
              "reg": [1, 0],
              "width": 802.95,
              "height": 322.4,
              "transformX": 424.5,
              "transformY": 617.95,
              "scaleX": 1,
              "scaleY": 1,
              "rotation": 0,
              "name": "_agWindow",
              "dom": [{
                "type": "layer",
                "x": 0,
                "y": 0,
                "name": "图层 1",
                "frameLen": 1,
                "frames": [{
                  "type": "frame",
                  "x": 0,
                  "y": 0,
                  "startFrame": 0,
                  "elements": [],
                  "duration": 1
                }]
              },
              {
                "type": "layer",
                "x": 0,
                "y": 0,
                "name": "图层 2",
                "frameLen": 1,
                "frames": [{
                  "type": "frame",
                  "x": 0,
                  "y": 0,
                  "startFrame": 0,
                  "elements": [{
                    "type": "button",
                    "x": 554.7,
                    "y": 143.8,
                    "reg": [0, 1],
                    "width": 93,
                    "height": 31,
                    "transformX": 554.7,
                    "transformY": 143.8,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_activedButton",
                    "src": "testFla_马场2.psd_资源_激活.png"
                  },
                  {
                    "type": "button",
                    "x": 567.35,
                    "y": 113.7,
                    "reg": [0, 1],
                    "width": 86,
                    "height": 30,
                    "transformX": 567.35,
                    "transformY": 113.7,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_confirmButton",
                    "src": "testFla_确定按钮.png"
                  },
                  {
                    "type": "movie clip",
                    "blendMode": "normal",
                    "x": 46.35,
                    "y": 82.8,
                    "reg": [1, 1],
                    "width": 70,
                    "height": 90,
                    "transformX": 87.35,
                    "transformY": 136.3,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_grid01",
                    "dom": [{
                      "type": "layer",
                      "x": 0,
                      "y": 0,
                      "name": "图层 2",
                      "frameLen": 1,
                      "frames": [{
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 0,
                        "elements": [],
                        "duration": 1
                      }]
                    },
                    {
                      "type": "layer",
                      "x": 0,
                      "y": 0,
                      "name": "图层 1",
                      "frameLen": 1,
                      "frames": [{
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 0,
                        "elements": [{
                          "type": "bitmap",
                          "src": "testFla_动物头像格子.png.png",
                          "x": 3,
                          "y": 0,
                          "reg": [0, 1],
                          "width": 70,
                          "height": 90,
                          "transformX": 38,
                          "transformY": 45,
                          "scaleX": 1,
                          "scaleY": 1,
                          "rotation": 0
                        }],
                        "duration": 1
                      }]
                    },
                    {
                      "type": "layer",
                      "x": 0,
                      "y": 0,
                      "name": "图层 3",
                      "frameLen": 1,
                      "frames": [{
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 0,
                        "elements": [],
                        "duration": 1
                      }]
                    }],
                    "frameLen": 1
                  },
                  {
                    "type": "movie clip",
                    "blendMode": "normal",
                    "x": 144.05,
                    "y": 82.8,
                    "reg": [1, 1],
                    "width": 70,
                    "height": 90,
                    "transformX": 185.05,
                    "transformY": 136.3,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_grid02",
                    "dom": [{
                      "type": "layer",
                      "x": 0,
                      "y": 0,
                      "name": "图层 2",
                      "frameLen": 1,
                      "frames": [{
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 0,
                        "elements": [],
                        "duration": 1
                      }]
                    },
                    {
                      "type": "layer",
                      "x": 0,
                      "y": 0,
                      "name": "图层 1",
                      "frameLen": 1,
                      "frames": [{
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 0,
                        "elements": [{
                          "type": "bitmap",
                          "src": "testFla_动物头像格子.png.png",
                          "x": 3,
                          "y": 0,
                          "reg": [0, 1],
                          "width": 70,
                          "height": 90,
                          "transformX": 38,
                          "transformY": 45,
                          "scaleX": 1,
                          "scaleY": 1,
                          "rotation": 0
                        }],
                        "duration": 1
                      }]
                    },
                    {
                      "type": "layer",
                      "x": 0,
                      "y": 0,
                      "name": "图层 3",
                      "frameLen": 1,
                      "frames": [{
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 0,
                        "elements": [],
                        "duration": 1
                      }]
                    }],
                    "frameLen": 1
                  },
                  {
                    "type": "movie clip",
                    "blendMode": "normal",
                    "x": 241.75,
                    "y": 82.8,
                    "reg": [1, 1],
                    "width": 70,
                    "height": 90,
                    "transformX": 282.75,
                    "transformY": 136.3,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_grid03",
                    "dom": [{
                      "type": "layer",
                      "x": 0,
                      "y": 0,
                      "name": "图层 2",
                      "frameLen": 1,
                      "frames": [{
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 0,
                        "elements": [],
                        "duration": 1
                      }]
                    },
                    {
                      "type": "layer",
                      "x": 0,
                      "y": 0,
                      "name": "图层 1",
                      "frameLen": 1,
                      "frames": [{
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 0,
                        "elements": [{
                          "type": "bitmap",
                          "src": "testFla_动物头像格子.png.png",
                          "x": 3,
                          "y": 0,
                          "reg": [0, 1],
                          "width": 70,
                          "height": 90,
                          "transformX": 38,
                          "transformY": 45,
                          "scaleX": 1,
                          "scaleY": 1,
                          "rotation": 0
                        }],
                        "duration": 1
                      }]
                    },
                    {
                      "type": "layer",
                      "x": 0,
                      "y": 0,
                      "name": "图层 3",
                      "frameLen": 1,
                      "frames": [{
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 0,
                        "elements": [],
                        "duration": 1
                      }]
                    }],
                    "frameLen": 1
                  },
                  {
                    "type": "movie clip",
                    "blendMode": "normal",
                    "x": 339.45,
                    "y": 82.8,
                    "reg": [1, 1],
                    "width": 70,
                    "height": 90,
                    "transformX": 380.45,
                    "transformY": 136.3,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_grid04",
                    "dom": [{
                      "type": "layer",
                      "x": 0,
                      "y": 0,
                      "name": "图层 2",
                      "frameLen": 1,
                      "frames": [{
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 0,
                        "elements": [],
                        "duration": 1
                      }]
                    },
                    {
                      "type": "layer",
                      "x": 0,
                      "y": 0,
                      "name": "图层 1",
                      "frameLen": 1,
                      "frames": [{
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 0,
                        "elements": [{
                          "type": "bitmap",
                          "src": "testFla_动物头像格子.png.png",
                          "x": 3,
                          "y": 0,
                          "reg": [0, 1],
                          "width": 70,
                          "height": 90,
                          "transformX": 38,
                          "transformY": 45,
                          "scaleX": 1,
                          "scaleY": 1,
                          "rotation": 0
                        }],
                        "duration": 1
                      }]
                    },
                    {
                      "type": "layer",
                      "x": 0,
                      "y": 0,
                      "name": "图层 3",
                      "frameLen": 1,
                      "frames": [{
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 0,
                        "elements": [],
                        "duration": 1
                      }]
                    }],
                    "frameLen": 1
                  },
                  {
                    "type": "movie clip",
                    "blendMode": "normal",
                    "x": 437.15,
                    "y": 82.8,
                    "reg": [1, 1],
                    "width": 70,
                    "height": 90,
                    "transformX": 478.15,
                    "transformY": 136.3,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_grid05",
                    "dom": [{
                      "type": "layer",
                      "x": 0,
                      "y": 0,
                      "name": "图层 2",
                      "frameLen": 1,
                      "frames": [{
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 0,
                        "elements": [],
                        "duration": 1
                      }]
                    },
                    {
                      "type": "layer",
                      "x": 0,
                      "y": 0,
                      "name": "图层 1",
                      "frameLen": 1,
                      "frames": [{
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 0,
                        "elements": [{
                          "type": "bitmap",
                          "src": "testFla_动物头像格子.png.png",
                          "x": 3,
                          "y": 0,
                          "reg": [0, 1],
                          "width": 70,
                          "height": 90,
                          "transformX": 38,
                          "transformY": 45,
                          "scaleX": 1,
                          "scaleY": 1,
                          "rotation": 0
                        }],
                        "duration": 1
                      }]
                    },
                    {
                      "type": "layer",
                      "x": 0,
                      "y": 0,
                      "name": "图层 3",
                      "frameLen": 1,
                      "frames": [{
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 0,
                        "elements": [],
                        "duration": 1
                      }]
                    }],
                    "frameLen": 1
                  },
                  {
                    "type": "text",
                    "x": -149.6,
                    "y": 82.8,
                    "reg": [0, 1],
                    "width": 160.6,
                    "height": 86,
                    "transformX": -69.3,
                    "transformY": 125.8,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_desc",
                    "textType": "dynamic",
                    "fontSize": 12,
                    "fillColor": "#ffffff",
                    "fontName": "宋体",
                    "alignment": "left",
                    "embedString": "  在牧场中养殖动物过饲养时间动物成熟之后，选择伙伴收获就能给伙伴正佳经验！不同的动物获得的经验不同，可以点击当前亮着的动物头像来刷新可养殖的动物种类。",
                    "lineType": "multiline"
                  },
                  {
                    "type": "button",
                    "x": 444.2,
                    "y": 148.8,
                    "reg": [0, 1],
                    "width": 62,
                    "height": 20.6,
                    "transformX": 444.2,
                    "transformY": 148.8,
                    "scaleX": 0.666656494140625,
                    "scaleY": 0.664520263671875,
                    "rotation": 0,
                    "name": "_maxLevelButton",
                    "src": "testFla_马场2.psd_资源_满级.png"
                  },
                  {
                    "type": "button",
                    "x": -145.9,
                    "y": 93.7,
                    "reg": [0, 1],
                    "width": 152,
                    "height": 54,
                    "transformX": -145.9,
                    "transformY": 93.7,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_close",
                    "src": "testFla_马场2.psd_资源_离开.png"
                  },
                  {
                    "type": "movie clip",
                    "blendMode": "screen",
                    "x": 352.2,
                    "y": -147.6,
                    "reg": [0, 1],
                    "width": 130,
                    "height": 130,
                    "transformX": 351.8,
                    "transformY": -147.25,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_texiao",
                    "dom": [{
                      "type": "layer",
                      "x": 0,
                      "y": 0,
                      "name": "图层 1",
                      "frameLen": 19,
                      "frames": [{
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 0,
                        "elements": [{
                          "type": "bitmap",
                          "src": "testFla_005_2_00000.png.png",
                          "x": 0,
                          "y": 0,
                          "reg": [0, 1],
                          "width": 130,
                          "height": 130,
                          "transformX": 65,
                          "transformY": 65,
                          "scaleX": 1,
                          "scaleY": 1,
                          "rotation": 0
                        }],
                        "duration": 2
                      },
                      {
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 2,
                        "elements": [{
                          "type": "bitmap",
                          "src": "testFla_005_2_00001.png.png",
                          "x": 0,
                          "y": 0,
                          "reg": [0, 1],
                          "width": 130,
                          "height": 130,
                          "transformX": 65,
                          "transformY": 65,
                          "scaleX": 1,
                          "scaleY": 1,
                          "rotation": 0
                        }],
                        "duration": 2
                      },
                      {
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 4,
                        "elements": [{
                          "type": "bitmap",
                          "src": "testFla_005_2_00002.png.png",
                          "x": 0,
                          "y": 0,
                          "reg": [0, 1],
                          "width": 130,
                          "height": 130,
                          "transformX": 65,
                          "transformY": 65,
                          "scaleX": 1,
                          "scaleY": 1,
                          "rotation": 0
                        }],
                        "duration": 2
                      },
                      {
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 6,
                        "elements": [{
                          "type": "bitmap",
                          "src": "testFla_005_2_00003.png.png",
                          "x": 0,
                          "y": 0,
                          "reg": [0, 1],
                          "width": 130,
                          "height": 130,
                          "transformX": 65,
                          "transformY": 65,
                          "scaleX": 1,
                          "scaleY": 1,
                          "rotation": 0
                        }],
                        "duration": 2
                      },
                      {
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 8,
                        "elements": [{
                          "type": "bitmap",
                          "src": "testFla_005_2_00004.png.png",
                          "x": 0,
                          "y": 0,
                          "reg": [0, 1],
                          "width": 130,
                          "height": 130,
                          "transformX": 65,
                          "transformY": 65,
                          "scaleX": 1,
                          "scaleY": 1,
                          "rotation": 0
                        }],
                        "duration": 2
                      },
                      {
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 10,
                        "elements": [{
                          "type": "bitmap",
                          "src": "testFla_005_2_00005.png.png",
                          "x": 0,
                          "y": 0,
                          "reg": [0, 1],
                          "width": 130,
                          "height": 130,
                          "transformX": 65,
                          "transformY": 65,
                          "scaleX": 1,
                          "scaleY": 1,
                          "rotation": 0
                        }],
                        "duration": 2
                      },
                      {
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 12,
                        "elements": [{
                          "type": "bitmap",
                          "src": "testFla_005_2_00006.png.png",
                          "x": 0,
                          "y": 0,
                          "reg": [0, 1],
                          "width": 130,
                          "height": 130,
                          "transformX": 65,
                          "transformY": 65,
                          "scaleX": 1,
                          "scaleY": 1,
                          "rotation": 0
                        }],
                        "duration": 2
                      },
                      {
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 14,
                        "elements": [{
                          "type": "bitmap",
                          "src": "testFla_005_2_00007.png.png",
                          "x": 0,
                          "y": 0,
                          "reg": [0, 1],
                          "width": 130,
                          "height": 130,
                          "transformX": 65,
                          "transformY": 65,
                          "scaleX": 1,
                          "scaleY": 1,
                          "rotation": 0
                        }],
                        "duration": 2
                      },
                      {
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 16,
                        "elements": [{
                          "type": "bitmap",
                          "src": "testFla_005_2_00008.png.png",
                          "x": 0,
                          "y": 0,
                          "reg": [0, 1],
                          "width": 130,
                          "height": 130,
                          "transformX": 65,
                          "transformY": 65,
                          "scaleX": 1,
                          "scaleY": 1,
                          "rotation": 0
                        }],
                        "duration": 2
                      },
                      {
                        "type": "frame",
                        "x": 0,
                        "y": 0,
                        "startFrame": 18,
                        "elements": [{
                          "type": "bitmap",
                          "src": "testFla_005_2_00008.png.png",
                          "x": 0,
                          "y": 0,
                          "reg": [0, 1],
                          "width": 130,
                          "height": 130,
                          "transformX": 65,
                          "transformY": 65,
                          "scaleX": 1,
                          "scaleY": 1,
                          "rotation": 0
                        }],
                        "duration": 1
                      }]
                    }],
                    "frameLen": 19
                  },
                  {
                    "type": "button",
                    "x": 345.95,
                    "y": 148.8,
                    "reg": [0, 1],
                    "width": 62,
                    "height": 20.6,
                    "transformX": 345.95,
                    "transformY": 148.8,
                    "scaleX": 0.666656494140625,
                    "scaleY": 0.664520263671875,
                    "rotation": 0,
                    "name": "_4button",
                    "src": "testFla_马场2.psd_资源_满级.png"
                  },
                  {
                    "type": "button",
                    "x": 247.7,
                    "y": 148.8,
                    "reg": [0, 1],
                    "width": 62,
                    "height": 20.6,
                    "transformX": 247.7,
                    "transformY": 148.8,
                    "scaleX": 0.666656494140625,
                    "scaleY": 0.664520263671875,
                    "rotation": 0,
                    "name": "_3button",
                    "src": "testFla_马场2.psd_资源_满级.png"
                  },
                  {
                    "type": "button",
                    "x": 151.45,
                    "y": 148.8,
                    "reg": [0, 1],
                    "width": 62,
                    "height": 20.6,
                    "transformX": 151.45,
                    "transformY": 148.8,
                    "scaleX": 0.666656494140625,
                    "scaleY": 0.664520263671875,
                    "rotation": 0,
                    "name": "_2button",
                    "src": "testFla_马场2.psd_资源_满级.png"
                  },
                  {
                    "type": "button",
                    "x": 53.2,
                    "y": 148.8,
                    "reg": [0, 1],
                    "width": 62,
                    "height": 20.55,
                    "transformX": 53.2,
                    "transformY": 148.8,
                    "scaleX": 0.666656494140625,
                    "scaleY": 0.66290283203125,
                    "rotation": 0,
                    "name": "_1button",
                    "src": "testFla_马场2.psd_资源_满级.png"
                  }],
                  "duration": 1
                }]
              },
              {
                "type": "layer",
                "x": 0,
                "y": 0,
                "name": "图层 4",
                "frameLen": 1,
                "frames": [{
                  "type": "frame",
                  "x": 0,
                  "y": 0,
                  "startFrame": 0,
                  "elements": [{
                    "type": "text",
                    "x": 52.75,
                    "y": 150.1,
                    "reg": [0, 1],
                    "width": 62.95,
                    "height": 16,
                    "transformX": 84.2,
                    "transformY": 158.1,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_name01",
                    "textType": "dynamic",
                    "fontSize": 12,
                    "fillColor": "#ffffff",
                    "fontName": "宋体",
                    "alignment": "center",
                    "embedString": "鸡",
                    "lineType": "multiline"
                  },
                  {
                    "type": "text",
                    "x": 150.75,
                    "y": 150.1,
                    "reg": [0, 1],
                    "width": 62.95,
                    "height": 16,
                    "transformX": 182.2,
                    "transformY": 158.1,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_name02",
                    "textType": "dynamic",
                    "fontSize": 12,
                    "fillColor": "#ffffff",
                    "fontName": "宋体",
                    "alignment": "center",
                    "embedString": "牛",
                    "lineType": "single line"
                  },
                  {
                    "type": "text",
                    "x": 248.75,
                    "y": 150.1,
                    "reg": [0, 1],
                    "width": 62.95,
                    "height": 16,
                    "transformX": 280.2,
                    "transformY": 158.1,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_name03",
                    "textType": "dynamic",
                    "fontSize": 12,
                    "fillColor": "#ffffff",
                    "fontName": "宋体",
                    "alignment": "center",
                    "embedString": "羊",
                    "lineType": "single line"
                  },
                  {
                    "type": "text",
                    "x": 346.75,
                    "y": 150.1,
                    "reg": [0, 1],
                    "width": 62.95,
                    "height": 16,
                    "transformX": 378.2,
                    "transformY": 158.1,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_name04",
                    "textType": "dynamic",
                    "fontSize": 12,
                    "fillColor": "#ffffff",
                    "fontName": "宋体",
                    "alignment": "center",
                    "embedString": "马",
                    "lineType": "single line"
                  },
                  {
                    "type": "text",
                    "x": 444.75,
                    "y": 150.1,
                    "reg": [0, 1],
                    "width": 62.95,
                    "height": 16,
                    "transformX": 476.2,
                    "transformY": 158.1,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_name05",
                    "textType": "dynamic",
                    "fontSize": 12,
                    "fillColor": "#ffffff",
                    "fontName": "宋体",
                    "alignment": "center",
                    "embedString": "金鹰",
                    "lineType": "single line"
                  }],
                  "duration": 1
                }]
              },
              {
                "type": "layer",
                "x": 0,
                "y": 0,
                "name": "图层 3",
                "frameLen": 1,
                "frames": [{
                  "type": "frame",
                  "x": 0,
                  "y": 0,
                  "startFrame": 0,
                  "elements": [],
                  "duration": 1
                }]
              }],
              "frameLen": 1
            }],
            "duration": 1
          }]
        },
        {
          "type": "layer",
          "x": 0,
          "y": 0,
          "name": "选择界面",
          "frameLen": 1,
          "frames": [{
            "type": "frame",
            "x": 0,
            "y": 0,
            "startFrame": 0,
            "elements": [{
              "type": "movie clip",
              "blendMode": "normal",
              "x": 526,
              "y": 58,
              "reg": [1, 0],
              "width": 100,
              "height": 76,
              "transformX": 784.5,
              "transformY": 278,
              "scaleX": 1,
              "scaleY": 1,
              "rotation": 0,
              "name": "_choiceWindow",
              "dom": [{
                "type": "layer",
                "x": 0,
                "y": 0,
                "name": "图层 3",
                "frameLen": 1,
                "frames": [{
                  "type": "frame",
                  "x": 0,
                  "y": 0,
                  "startFrame": 0,
                  "elements": [],
                  "duration": 1
                }]
              },
              {
                "type": "layer",
                "x": 0,
                "y": 0,
                "name": "图层 2",
                "frameLen": 1,
                "frames": [{
                  "type": "frame",
                  "x": 0,
                  "y": 0,
                  "startFrame": 0,
                  "elements": [{
                    "type": "button",
                    "x": 235.35,
                    "y": 63.95,
                    "reg": [0, 1],
                    "width": 100,
                    "height": 35.5,
                    "transformX": 235.35,
                    "transformY": 63.95,
                    "scaleX": 0.65789794921875,
                    "scaleY": 0.65740966796875,
                    "rotation": 0,
                    "name": "_breedButton",
                    "src": "testFla_马场2.psd_资源_养殖.png"
                  },
                  {
                    "type": "button",
                    "x": 235.35,
                    "y": 23.45,
                    "reg": [0, 1],
                    "width": 100,
                    "height": 35.4,
                    "transformX": 235.35,
                    "transformY": 23.45,
                    "scaleX": 0.65789794921875,
                    "scaleY": 0.655548095703125,
                    "rotation": 0,
                    "name": "_upgradeButton",
                    "src": "testFla_马场2.psd_资源_升级.png"
                  }],
                  "duration": 1
                }]
              },
              {
                "type": "layer",
                "x": 0,
                "y": 0,
                "name": "图层 1",
                "frameLen": 1,
                "frames": [{
                  "type": "frame",
                  "x": 0,
                  "y": 0,
                  "startFrame": 0,
                  "elements": [],
                  "duration": 1
                }]
              }],
              "frameLen": 1
            }],
            "duration": 1
          }]
        },
        {
          "type": "layer",
          "x": 0,
          "y": 0,
          "name": "升级窝棚",
          "frameLen": 1,
          "frames": [{
            "type": "frame",
            "x": 0,
            "y": 0,
            "startFrame": 0,
            "elements": [{
              "type": "movie clip",
              "blendMode": "normal",
              "x": 679.95,
              "y": 108.5,
              "reg": [0, 1],
              "width": 153,
              "height": 172.95,
              "transformX": 938.45,
              "transformY": 328.6,
              "scaleX": 1,
              "scaleY": 1,
              "rotation": 0,
              "name": "_upgradeWindow",
              "dom": [{
                "type": "layer",
                "x": 0,
                "y": 0,
                "name": "图层 3",
                "frameLen": 1,
                "frames": [{
                  "type": "frame",
                  "x": 0,
                  "y": 0,
                  "startFrame": 0,
                  "elements": [],
                  "duration": 1
                }]
              },
              {
                "type": "layer",
                "x": 0,
                "y": 0,
                "name": "图层 1",
                "frameLen": 1,
                "frames": [{
                  "type": "frame",
                  "x": 0,
                  "y": 0,
                  "startFrame": 0,
                  "elements": [],
                  "duration": 1
                }]
              },
              {
                "type": "layer",
                "x": 0,
                "y": 0,
                "name": "图层 2",
                "frameLen": 1,
                "frames": [{
                  "type": "frame",
                  "x": 0,
                  "y": 0,
                  "startFrame": 0,
                  "elements": [{
                    "type": "text",
                    "x": 0.05,
                    "y": 66.95,
                    "reg": [0, 1],
                    "width": 150,
                    "height": 16,
                    "transformX": 75.05,
                    "transformY": 74.95,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_currLevel",
                    "textType": "dynamic",
                    "fontSize": 12,
                    "fillColor": "#ffffff",
                    "fontName": "宋体",
                    "alignment": "center",
                    "embedString": "当前等级：",
                    "lineType": "multiline"
                  },
                  {
                    "type": "text",
                    "x": 0.05,
                    "y": 92.95,
                    "reg": [0, 1],
                    "width": 150,
                    "height": 16,
                    "transformX": 75.05,
                    "transformY": 100.95,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_currNum",
                    "textType": "dynamic",
                    "fontSize": 12,
                    "fillColor": "#ffffff",
                    "fontName": "宋体",
                    "alignment": "center",
                    "embedString": "当前饲养数量：",
                    "lineType": "multiline"
                  },
                  {
                    "type": "text",
                    "x": 0.05,
                    "y": 120,
                    "reg": [0, 1],
                    "width": 150,
                    "height": 16,
                    "transformX": 75.05,
                    "transformY": 128,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_newLevel",
                    "textType": "dynamic",
                    "fontSize": 12,
                    "fillColor": "#ffffff",
                    "fontName": "宋体",
                    "alignment": "center",
                    "embedString": "升级后等级：",
                    "lineType": "multiline"
                  },
                  {
                    "type": "text",
                    "x": 0.05,
                    "y": 146,
                    "reg": [0, 1],
                    "width": 150,
                    "height": 16,
                    "transformX": 75.05,
                    "transformY": 154,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_newNum",
                    "textType": "dynamic",
                    "fontSize": 12,
                    "fillColor": "#ffffff",
                    "fontName": "宋体",
                    "alignment": "center",
                    "embedString": "升级后饲养数量：",
                    "lineType": "multiline"
                  },
                  {
                    "type": "text",
                    "x": 0.05,
                    "y": 156.95,
                    "reg": [0, 1],
                    "width": 141.9,
                    "height": 16,
                    "transformX": 71,
                    "transformY": 164.95,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_moneyNum",
                    "textType": "dynamic",
                    "fontSize": 12,
                    "fillColor": "#ffffff",
                    "fontName": "宋体",
                    "alignment": "center",
                    "embedString": "升级所需：100元宝",
                    "lineType": "multiline"
                  },
                  {
                    "type": "text",
                    "x": 0.05,
                    "y": 72.4,
                    "reg": [0, 1],
                    "width": 152.95,
                    "height": 71.65,
                    "transformX": 76.5,
                    "transformY": 108.2,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_dialog",
                    "textType": "dynamic",
                    "fontSize": 12,
                    "fillColor": "#ffffff",
                    "fontName": "宋体",
                    "alignment": "left",
                    "embedString": "",
                    "lineType": "multiline"
                  },
                  {
                    "type": "button",
                    "x": 77.45,
                    "y": 3,
                    "reg": [0, 1],
                    "width": 39,
                    "height": 38,
                    "transformX": 77.45,
                    "transformY": 3,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_uCloseButton",
                    "src": "testFla_升级窝棚界面关闭.png"
                  },
                  {
                    "type": "button",
                    "x": 0,
                    "y": 0,
                    "reg": [0, 1],
                    "width": 41,
                    "height": 35,
                    "transformX": 0,
                    "transformY": 0,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_ub",
                    "src": "testFla_按钮_样式2.png"
                  }],
                  "duration": 1
                }]
              }],
              "frameLen": 1
            }],
            "duration": 1
          }]
        },
        {
          "type": "layer",
          "x": 0,
          "y": 0,
          "name": "收获界面",
          "frameLen": 1,
          "frames": [{
            "type": "frame",
            "x": 0,
            "y": 0,
            "startFrame": 0,
            "elements": [{
              "type": "movie clip",
              "blendMode": "normal",
              "x": 283.3,
              "y": 160.3,
              "reg": [0, 1],
              "width": 347,
              "height": 215,
              "transformX": 533.3,
              "transformY": 260.3,
              "scaleX": 1,
              "scaleY": 1,
              "rotation": 0,
              "name": "_shouhuoWindow",
              "dom": [{
                "type": "layer",
                "x": 0,
                "y": 0,
                "name": "图层 1",
                "frameLen": 1,
                "frames": [{
                  "type": "frame",
                  "x": 0,
                  "y": 0,
                  "startFrame": 0,
                  "elements": [{
                    "type": "bitmap",
                    "src": "testFla_收获界面.png.png",
                    "x": 0,
                    "y": 0,
                    "reg": [0, 1],
                    "width": 347,
                    "height": 215,
                    "transformX": 173.5,
                    "transformY": 107.5,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0
                  },
                  {
                    "type": "bitmap",
                    "src": "testFla_头像背景图.png.png",
                    "x": 28,
                    "y": 50,
                    "reg": [0, 1],
                    "width": 89,
                    "height": 86,
                    "transformX": 72.5,
                    "transformY": 93,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0
                  },
                  {
                    "type": "button",
                    "x": 309.85,
                    "y": 4,
                    "reg": [0, 1],
                    "width": 29,
                    "height": 30,
                    "transformX": 309.85,
                    "transformY": 4,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_help",
                    "src": "testFla_问号.png"
                  }],
                  "duration": 1
                }]
              },
              {
                "type": "layer",
                "x": 0,
                "y": 0,
                "name": "图层 2",
                "frameLen": 1,
                "frames": [{
                  "type": "frame",
                  "x": 0,
                  "y": 0,
                  "startFrame": 0,
                  "elements": [],
                  "duration": 1
                }]
              },
              {
                "type": "layer",
                "x": 0,
                "y": 0,
                "name": "图层 3",
                "frameLen": 1,
                "frames": [{
                  "type": "frame",
                  "x": 0,
                  "y": 0,
                  "startFrame": 0,
                  "elements": [{
                    "type": "button",
                    "x": 205.3,
                    "y": 157.95,
                    "reg": [0, 1],
                    "width": 71,
                    "height": 30,
                    "transformX": 205.3,
                    "transformY": 157.95,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_buttonQuxiao",
                    "src": "testFla_取消1.png"
                  },
                  {
                    "type": "button",
                    "x": 57.3,
                    "y": 157.95,
                    "reg": [0, 1],
                    "width": 71,
                    "height": 30,
                    "transformX": 57.3,
                    "transformY": 157.95,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_buttonShouhuo",
                    "src": "testFla_收获1.png"
                  },
                  {
                    "type": "text",
                    "x": 58.95,
                    "y": 137.7,
                    "reg": [0, 1],
                    "width": 222,
                    "height": 16,
                    "transformX": 169.95,
                    "transformY": 145.7,
                    "scaleX": 1,
                    "scaleY": 1,
                    "rotation": 0,
                    "name": "_expInfo",
                    "textType": "dynamic",
                    "fontSize": 12,
                    "fillColor": "#ffffff",
                    "fontName": "宋体",
                    "alignment": "center",
                    "embedString": "aaaaaaaaaaaaaaaaaaaaaaaaaa",
                    "lineType": "single line"
                  }],
                  "duration": 1
                }]
              }],
              "frameLen": 1
            }],
            "duration": 1
          }]
        },
        {
          "type": "layer",
          "x": 0,
          "y": 0,
          "name": "功能层",
          "frameLen": 1,
          "frames": [{
            "type": "frame",
            "x": 0,
            "y": 0,
            "startFrame": 0,
            "elements": [{
              "type": "button",
              "x": 837.8,
              "y": 5.85,
              "reg": [0, 1],
              "width": 29,
              "height": 29,
              "transformX": 837.8,
              "transformY": 5.85,
              "scaleX": 1,
              "scaleY": 1,
              "rotation": 0,
              "name": "_closebutton",
              "src": "testFla_关闭.png"
            },
            {
              "type": "button",
              "x": 810.8,
              "y": 4,
              "reg": [0, 1],
              "width": 29,
              "height": 30,
              "transformX": 810.8,
              "transformY": 4,
              "scaleX": 1,
              "scaleY": 1,
              "rotation": 0,
              "name": "_help",
              "src": "testFla_问号.png"
            }],
            "duration": 1
          }]
        }],
        "frameLen": 1
      }],
      "duration": 1
    }]
  }],
  "frameLen": 1
}